### ISSUE TITLE
rdkit failing to kekulize molecules

### ISSUE THREAD

**Issue by stefdoerr** [Acellera/parameterize#14]
Maybe this is more of a moleculekit issue but I'll leave it here because it's the most frequent case of issues in parameterize. 
Example SMILES:
`C1=CC(=C(C=C1O)O)C2=C(C(=O)C3=C(C=C(C=C3O2)O)O)O`

**Comment by raimis** [comment]
Potentially fixed by #18

**Comment by stefdoerr** [comment]
Works on current PM application
