### ISSUE TITLE
RuntimeError: No Slurm configuration YAML file defined for the configapp

### ISSUE THREAD

**Issue by eduardodinizRO** [Acellera/parameterize#29]
Hello!
I've been attempting to run parameterize on a computer cluster  using the following recommended command line on the manual:
 parameterize  xxx.mol2 --charge xx --queue Slurm --outdir slurm

but the job always ends with:

 RuntimeError: No Slurm configuration YAML file defined for the configapp

I've installed psi4 and parameterize on an environment created just for these programs with the following commands:
conda create -n p4env python=3.6 psi4 psi4-rt -c psi4/label/dev -c psi4
conda activate p4env
conda install -c acellera -c psi4 -c conda-forge parameterize

When I omit the option --queue (setting for local by default) the job terminates with segmentation fault.

Is there any suggestion on how to proceed? Thank you.

**Comment by stefdoerr** [comment]
Again sorry for the very late answer but for future users you can look up the solution here
https://github.com/Acellera/parameterize/issues/34#issuecomment-990925838
