### ISSUE TITLE
PlayMolecule 'babel' error

### ISSUE THREAD

**Issue by dominicrufa** [Acellera/parameterize#30]
I'm encountering an error in the PlayMolecule GUI concerning a 'babel' no file or directory error when I attempt to draw a molecule and parameterize it. Any help here would be appreciated. Thanks!

![image](https://user-images.githubusercontent.com/46943710/100619585-63eb4b00-32eb-11eb-82df-5d24a3ea2fe5.png)

**Comment by stefdoerr** [comment]
Hi Dominic. Thanks for bringing the issue to our attention. I will fix it shortly and report back.

**Comment by dominicrufa** [comment]
great! thanks. i should also mention the same error is thrown when one inputs a smiles string or loads an sdf/mol2

**Comment by stefdoerr** [comment]
Hi, I found the cause. An update in openbabel software changed the executable from `babel` to `obabel`. I fixed it now but it might take me one/two days to deploy the fix since it's coming with a few more upcoming fixes for other apps. I'll write back once it's available.

**Comment by dominicrufa** [comment]
great! i look forward to it. thanks!

**Comment by stefdoerr** [comment]
Hey @dominicrufa . The issue is fixed and deployed on playmolecule.com 
Give it a try now :) 
Best,
Stefan
