### ISSUE TITLE
ANI-2x question

### ISSUE THREAD

**Issue by tantrev** [Acellera/parameterize#31]
Hi there,

I noticed that the PlayMolecule site permits the use of "ANI-2x" for parameterizations with GAFF. I think the ANI functionality is awesome - I would just love to use such functionality with the CHARMM force field (and hence probably need to run parameterize locally).  It seems there is some code in this repository referencing "nnp" - is there any way to activate the ANI-2x functionality (it doesn't seem to be in the online documentation), and if so, can it be used with CHARMM?

Thank you in advance.

**Comment by stefdoerr** [comment]
Hi Trevor. Happy new year. 
Unfortunately Parameterize doesn't generate CHARMM parapeters even in standalone mode. You will need to use some conversion tool like acpype or parmed to convert them.
The standalone does not support ANI-2x officially, it's only part of the online application
