### ISSUE TITLE
Converting to .itp GROMACS file

### ISSUE THREAD

**Issue by ale94mleon** [Acellera/parameterize#33]
Hi, 
Could anyone suggest me a way to convert the "mol.frcmod" output to .itp GROMACS topology file?
Thanks in advance

**Comment by stefdoerr** [comment]
Sorry I don't have any experience with GROMACS at all. Try to search for tools which can convert frcmod files to itp.
Maybe `parmed` can do it.

**Comment by ale94mleon** [comment]
I saw that with `acpype.py -p mol.prmtop -x mol.inpcrd` I can obtein what I need. But, how I can obtein the .prmtop and .inpcrd using tleap?

**Comment by stefdoerr** [comment]
you can build the `prmtop` and `crd` which I assume is equivalent to `inpcrd` with the `amber.build()` command in HTMD. 

```python
from htmd.ui import *
mol = Molecule("./mol.mol2")
param = ["./mol.frcmod"]
amber.build(mol, param=param, ionize=False, outdir="./build")
```
This ought to create the files in the build folder

**Comment by ale94mleon** [comment]
This gives a nasty error (some part related with update, and the last part no idea :-). However, now I see that in the output directory (the default that is generated when the paramterize run ends) there is a file `tleap.in`, so I presume that this should be enough to solve my problem. Now I need to figure it out, how to use tleap. But that is another issue. Thanks Stefan Doer for your quick replies.

```
/home/users/all-jh/opt/miniconda3/envs/htmd/lib/python3.7/site-packages/htmd/versionwarnings.py:30: UserWarning: As of HTMD 1.16 the default number of threads HTMD spawns for calculations is set to 1. You can enable parallelism at your own risk using `config(njobs=-2)` in the beginning of your scripts. To disable this warning run once: `from htmd import _disableWarnings; _disableWarnings('1.16');`
  UserWarning,
/home/users/all-jh/opt/miniconda3/envs/htmd/lib/python3.7/site-packages/htmd/versionwarnings.py:38: UserWarning: As of HTMD 1.21 support for ACEMD v2 has stopped. Please use ACEMD3 instead as well as the corresponding equilibration and production protocols. To disable this warning run once: `from htmd import _disableWarnings; _disableWarnings('1.21');`
  UserWarning,

Please cite HTMD: Doerr et al.(2016)JCTC,12,1845. https://dx.doi.org/10.1021/acs.jctc.6b00049

HTMD Documentation at: https://www.htmd.org/docs/latest/

2021-04-26 19:35:43,516 - binstar - INFO - Using Anaconda API: https://api.anaconda.org
New devel HTMD version (1.24.7 python[3.6,<3.7.0a0,3.7,<3.8.0a0]) is available. You are currently on (1.23.7).There are several methods to update:    - Create a new conda env. using `conda create -n htmd1.24.7 htmd=1.24.7 -c acellera -c psi4 -c conda-forge`    - Create a brand new conda installation and run `conda install htmd -c acellera -c psi4 -c conda-forge`    - Run: `conda update htmd -c acellera -c psi4 -c conda-forge` (NOT RECOMMENDED)

Traceback (most recent call last):
  File "tak.py", line 4, in <module>
    amber.build(mol, param=param, ionize=False, outdir="./build")
  File "/home/users/all-jh/opt/miniconda3/envs/htmd/lib/python3.7/site-packages/htmd/builder/amber.py", line 310, in build
    _missingSegID(mol)
  File "/home/users/all-jh/opt/miniconda3/envs/htmd/lib/python3.7/site-packages/moleculekit/util.py", line 316, in _missingSegID
    raise RuntimeError('Atoms [' + str(idx[0]) + ',' + str(idx[1]) + ',...,' + str(idx[-1]) + '] do not have segid defined.')
RuntimeError: Atoms [0,1,...,10] do not have segid defined.
```

**Comment by stefdoerr** [comment]
This error is easy to fix. Just do
mol.segid[:] = "L"
Before the build command

**Comment by ale94mleon** [comment]
Yes, it works with mol.segid[:] = "L". :+1: 

Also the command:
`tleap -s -f tleap.in > tleap.out`
Works pretty well, I don't know if tleap is already in the HTMD environment, or if I installed severally. I guess that it was already in HTMD.
And them I run:
`acpype -p structure.prmtop -x mol.crd`
And everything is perfect, the .gro (the configuration) and .top (the topology, pretty much the same that .itp) files are obtained.
And I got acpype with:
`pip install git+https://github.com/alanwilter/acpype.git.`

**Comment by kexul** [comment]
Hi @stefdoerr , I parametrized a molecule using the `playmolecule` web application and retrieved the result zip. When trying to build the system using the code you mentioned above: 
```
from htmd.ui import *
mol = Molecule("./mol.mol2")
mol.segid[:] = "L"
param = ["./mol.frcmod"]
amber.build(mol, param=param, ionize=False, outdir="./build")
```
These error occurred: 
```
htmd.builder.builder.BuildError: MissingTorsionError("Missing torsion terms for ['cl-zb-ca-ha', 'za-zh-zj-hn', 'zk-zh-zj-hn', 'zk-zh-za-hc', 'zk-zh-za-hc', 'zk-zh-za-hc', 'zj-zf-ze-ha', 'zj-zh-za-hc', 'zj-zh-za-hc', 'zj-zh-za-hc', 'ze-zd-zi-hn', 'ze-zd-ca-ha', 'ze-zf-zj-zh', 'ze-zf-zj-hn', 'zf-zj-zh-zk', 'zf-zj-zh-za', 'nb-zf-ze-ha', 'nb-zf-zj-zh', 'nb-zf-zj-hn', 'ca-ca-zd-ze', 'ca-nb-zf-ze', 'ca-nb-zf-zj', 'ca-zd-zi-hn', 'ca-zd-ze-zf', 'ca-zd-ze-ha', 'zd-ze-zf-nb', 'zd-ze-zf-zj', 'zi-zd-ca-ca', 'zi-zd-ca-ha', 'zi-zd-ze-zf', 'zi-zd-ze-ha', 'zk-zg-zi-zd', 'zk-zg-zi-hn', 'zg-zc-zb-cl', 'zg-zi-zd-ca', 'zg-zi-zd-ze', 'cl-zb-zc-zg', 'cl-zb-ca-ha', 'ca-zb-zc-zg', 'zb-zc-zb-cl', 'zb-zc-zg-zk', 'zb-zc-zg-zi', 'zc-zb-ca-ha', 'zc-zb-ca-ha', 'zc-zg-zi-zd', 'zc-zg-zi-hn', 'zb-zc-zb-ca', 'zb-zc-zb-cl', 'zb-zc-zg-zk', 'zb-zc-zg-zi', 'ca-zb-zc-zb', 'ca-zb-zc-zg', 'ca-ca-zb-zc', 'ca-ca-zb-cl', 'ca-ca-zb-zc', 'ca-ca-zb-cl']")
MissingBondError("Missing bond parameters for ['zh - zk', 'zh - za', 'ze - ha', 'zf - zj', 'nb - zf', 'zd - ca', 'zd - ze', 'zi - zd', 'zi - hn', 'zg - zi', 'zb - ca', 'zb - cl', 'zc - zb', 'zc - zg', 'zb - zc', 'zb - cl', 'ca - zb']")
MissingAngleError("Missing angle parameters for ['zk - zh - za', 'zh - za - hc', 'zh - za - hc', 'zh - za - hc', 'zj - zh - zk', 'zj - zh - za', 'ze - zf - zj', 'zf - ze - ha', 'zf - zj - zh', 'zf - zj - hn', 'nb - zf - ze', 'nb - zf - zj', 'ca - nb - zf', 'ca - zd - ze', 'zd - zi - hn', 'zd - ca - ca', 'zd - ca - ha', 'zd - ze - zf', 'zd - ze - ha', 'zi - zd - ca', 'zi - zd - ze', 'zk - zg - zi', 'zg - zi - zd', 'zg - zi - hn', 'ca - zb - cl', 'zb - zc - zg', 'zb - ca - ha', 'zc - zb - cl', 'zc - zb - ca', 'zc - zb - cl', 'zc - zg - zk', 'zc - zg - zi', 'zb - ca - ha', 'zb - zc - zb', 'zb - zc - zg', 'ca - zb - zc', 'ca - zb - cl', 'ca - ca - zb', 'ca - ca - zb']")
```
Would you mind take a look where I'm doing wrong? Thanks!

Here are the input files I used:
[ejm_31.zip](https://github.com/Acellera/parameterize/files/7513277/ejm_31.zip)

**Comment by stefdoerr** [comment]
I just ran it and it works fine. Are you on the latest HTMD version?

This worked for me with the files you have in the zip

```
from htmd.ui import *
mol = Molecule("./mol.mol2")
param = ["./mol.frcmod"]
mol.segid[:] = "L"
amber.build(mol, param=param, ionize=False, outdir="/tmp/build")
```

**Comment by kexul** [comment]
> I just ran it and it works fine. Are you on the latest HTMD version?

Hi @stefdoerr , thanks for your quick reply, I'm using 
```
# Name                    Version                   Build  Channel
htmd                      1.23.7                   py37_0    acellera
``` 
installed by ` conda install -c acellera -c conda-forge htmd`, before that, I install parametrize by `conda install -c acellera -c psi4 -c conda-forge parameterize` in a newly created env. 
I tried to install the latest version by `conda install -c accellera -c conda-forge htmd==1.26.5`, which is the latest version I seen in conda, but the installation failed with package conflict. 
Then I tried installing htmd in a clean new env, but still encountered the same error. 

Do I need to clone the source code from github and compile it to install the latest version?

**Comment by kexul** [comment]
Update: Just deactivate the env and re-activate it, now it works fine. Thanks!
