### ISSUE TITLE
Bug in the declaration of the memory by psi4.py

### ISSUE THREAD

**Issue by ale94mleon** [Acellera/parameterize#34]
Hello, 
I have some issues when big bases sets are used and also MP2. For that psi4 recommend the following:
https://psicode.org/psi4manual/master/cc.html?highlight=swap#larger-calculations
However, for some reason, the ESP job take exactly the amount of memory that you declare in the command line when you launch parameterize, but the psi4.in calculation for the dihedral angles has the entire memory of my computer.
I don't understand why, because it looks like both inputs are created by the same method, but for some reason the value of queue.memory change between the instance created for the ESP and the one for the dihedral.
This is not big deal for "normal" basi set. But in my case that my computer has 31 GB of RAM is a problem. Because psi4 get in troubles for this large base set if the RAM is bigger than 16 GB, Any idea how to fix this.
I temporally just changed the line 134 in psi4,py:
`f.write("set_memory('{} MB')\n\n".format(self.queue.memory))`
by:
`f.write("set_memory('MY_RAM MB')\n\n")`
been MY_RAM the amount that I want to use, in my case 15 000
But this is a pretty ugly solution.

**Comment by stefdoerr** [comment]
Hi, this might be a ridiculously late answer but you can set queue variables like this:
```
export JOBQUEUES_CONFIG=/home/username/queues.yaml
```
and then in `queues.yaml` you can specify the resources like this:
```
psi4:
  memory: 2000 
```
For 2 GB for example
