### ISSUE TITLE
Problem with atom types for GAFF

### ISSUE THREAD

**Issue by jnoske** [Acellera/parameterize#35]
Hi, unfortunately parameterize assigns weird atom types like za or zb, that are not in GAFF and lead to problems when building with tleap since element they are unknown. Is there a way of fixing this ?

**Comment by stefdoerr** [comment]
Could you post the outputs? There should be no issue with these atom types because they are defined in the files produced by parameterize. The frcmod file contains their mass which defines their elements.

**Comment by jnoske** [comment]
The problem is that tleap from ambertools does not know these atom types and assigns -1, in the ATOM_NUMBER section of the resulting .prmtop file, which causes problems in later stages of my program. 
[prmtop.txt](https://github.com/Acellera/parameterize/files/7153114/prmtop.txt)
[ligand_mol2.txt](https://github.com/Acellera/parameterize/files/7153124/ligand_mol2.txt)

**Comment by stefdoerr** [comment]
How do you build the system? With HTMD or tleap directly? Can you share the script?

**Comment by jnoske** [comment]
I build them with HTMD.
[tleap_input.txt](https://github.com/Acellera/parameterize/files/7153148/tleap_input.txt)

**Comment by jnoske** [comment]
So unfortunately I have still no solution for the problem. Either something is wrong with tleap/htmd that there is no line adding these atom types or there should be no atom types in the frcmod files that are not in gaff. Can I make tleap understand these atomtypes from the masses defined in the frcmod file ?

**Comment by stefdoerr** [comment]
Can you provide me with the original mol2? I'll try to build it from scratch.

**Comment by jnoske** [comment]
Hi here is the file I protonated with openbabel, which assigned sybyl atomtypes. The problem is that I want to use parametrize to parametrize many ligands in high throughput, so this is really just a test case.
Why does parameterize assign atom types za and zb that are not in GAFF or why does tleap not get there element from atomic masses ?
[ligand.txt](https://github.com/Acellera/parameterize/files/7184605/ligand.txt)

**Comment by stefdoerr** [comment]
I ran it through parameterize and got this zip
[10EE15DF.zip](https://github.com/Acellera/parameterize/files/7184781/10EE15DF.zip)

Then I ran the following commands and it built fine for AMBER
```python
from htmd.ui import *
mol = Molecule("./mol.mol2")
mol.segid[:] = "L"
smol = solvate(mol, minmax=[[-10, -10, -10], [10, 10, 10]])
bmol = amber.build(smol, param=["mol.frcmod"], outdir="./build")

```

**Comment by jnoske** [comment]
Did you checked for any unknown atom type warnings in the tleap log ?

**Comment by stefdoerr** [comment]
Yes, it doesn't seem to matter though. It reads the masses fine from the frcmod file. Only thing it seems to affect is that it has -1 ATOMIC_NUMBER in the prmtop but otherwise behaves as expected as far as I can tell.

**Comment by jnoske** [comment]
Ok, so my problem is that there should be no -1 in the ATOMIC_NUMBER section, since it causes problems with openmm, so I will try to use antechamber and parmchk2 to change atom types to gaff and create a new .frcmod file from the parametrized ligand (mol.mol2), tat shoudl hopefully work.

**Comment by stefdoerr** [comment]
If you change atom types to GAFF you are losing the improved parameters of parameterize which beats the point. ACEMD3 seems to ignore the ATOMIC_NUMBER section (why use it anyway in MD if you already know the masses?). I would rather suggest you manually fix the atomic numbers if you want for this system if you care to use openMM.

**Comment by stefdoerr** [comment]
You could even automatically fix the prmtop if you are feeling adventurous by reading the masses and adding the corresponding atomic number in the -1s.

**Comment by stefdoerr** [comment]
To explain a bit better. These `z*` atom types are not a mistake. To improve GAFF2 parameters we need to create new atom types for each dihedral angle of your molecule so that they can be parameterized individually. So if you restore the original GAFF2 atom types you are losing the parameter improvements. In which case you can just run your molecule through GAFF2 directly without using parameterize.

**Comment by jnoske** [comment]
Yes I guess changing the ATOMIC NUMBER section is the best option for me. I will search for a mapping of atomic numbers and elements.

**Comment by jnoske** [comment]
But this doesnt cause problems in the resulting prmtop file describing the system in a wrong way since atom types are unknown ?

**Comment by stefdoerr** [comment]
Not really. All the atom properties necessary for simulation are defined correctly in the frcmod file for those atom types.

**Comment by jnoske** [comment]
Ok thank you, now that I understand, that it is not an issue I can solve the problem in a manual way.
