### ISSUE TITLE
Could Not Type Atom S1 With State S.4

### ISSUE THREAD

**Issue by jnoske** [Acellera/parameterize#40]
Hi,

I get the following error, when trying to parameterize the following ligand for CGenFF_2b6, because the Match-Typer fails.

#

@<TRIPOS>MOLECULE
3MOL_MOLand
 104 110 0 0 0
SMALL
USER_CHARGES

@<TRIPOS>ATOM
      1 C           2.4760   -9.7570   31.1330 C.2       1 MOL         0.2070
      2 N           1.3770  -11.7780   31.5120 N.am      1 MOL        -0.2407
      3 O           1.9560   -9.6360   30.0650 O.2       1 MOL        -0.3942
      4 CA          2.6250  -11.0070   31.6660 C.3       1 MOL         0.1378
      5 CB          3.9010  -11.7690   31.1510 C.3       1 MOL         0.0025
      6 CAB         0.4870  -11.9400   32.4950 C.2       1 MOL         0.3221
      7 NAC         2.5950   -5.6560   35.5540 N.ar      1 MOL        -0.2649
      8 CAD         0.4540   -3.3530   37.1790 C.ar      1 MOL        -0.0425
      9 CAE         3.1150   -3.9150   36.9200 C.ar      1 MOL        -0.0161
     10 CAF        -2.9650  -13.1150   33.0540 C.3       1 MOL        -0.0165
     11 CAG        -2.4620  -11.7730   33.4680 C.3       1 MOL        -0.0077
     12 CAH        -1.5080  -12.8960   33.2950 C.3       1 MOL         0.0914
     13 CAK         7.6460   -1.9430   28.4520 C.2       1 MOL        -0.0560
     14 CAL         6.2860   -1.7790   28.9500 C.2       1 MOL        -0.0560
     15 OAM         5.8900   -3.4560   26.3170 O.2       1 MOL        -0.1497
     16 SAN         6.2200   -4.2460   27.4200 S.O2      1 MOL         0.0716
     17 CAO         3.0140   -6.7220   27.7090 C.3       1 MOL         0.1374
     18 OAP         4.5290   -7.8200   29.7450 O.2       1 MOL        -0.3947
     19 CAQ         3.4920   -7.2800   30.0230 C.2       1 MOL         0.2013
     20 CAR         4.1810  -12.8780   32.1250 C.3       1 MOL        -0.0558
     21 CAS         3.2000   -8.5640   25.8730 C.3       1 MOL        -0.0516
     22 CAT         0.8600   -4.3950   36.4100 C.ar      1 MOL         0.0479
     23 CAU        -2.6010  -11.3050   34.8700 C.3       1 MOL        -0.0474
     24 NAV         4.9830   -5.1230   27.9380 N.am      1 MOL        -0.1546
     25 CAW         2.5120   -7.9920   27.0840 C.3       1 MOL        -0.0066
     26 CAX        -1.2050   -9.2640   34.7080 C.3       1 MOL        -0.0510
     27 CAY         1.3730   -2.5830   37.8230 C.ar      1 MOL        -0.0236
     28 OAZ         2.1540   -7.4020   34.2250 O.3       1 MOL        -0.2852
     29 CBA         4.9190   -2.2270   38.3330 C.3       1 MOL         0.0605
     30 OBB         3.5620   -2.0510   38.3700 O.3       1 MOL        -0.3183
     31 CBC        -2.5850   -9.8380   34.8740 C.3       1 MOL        -0.0525
     32 CBD        -1.0960   -7.9650   35.3470 C.3       1 MOL        -0.0406
     33 CBE         1.7410   -6.3910   34.9400 C.ar      1 MOL         0.1985
     34 CBF         0.3710   -6.1430   35.0590 C.ar      1 MOL         0.0906
     35 CBG         2.1960   -4.6710   36.2800 C.ar      1 MOL         0.0423
     36 NBH        -0.0160   -5.1350   35.8010 N.ar      1 MOL        -0.2829
     37 CBI        -0.6130   -6.9000   34.4340 C.3       1 MOL         0.0041
     38 CBJ         2.7250   -2.8500   37.7080 C.ar      1 MOL         0.0960
     39 OBK         7.2670   -5.0730   26.9790 O.2       1 MOL        -0.1497
     40 CBL         6.8750   -3.1150   28.8700 C.3       1 MOL         0.1367
     41 OBM         4.4810   -5.9790   25.9480 O.2       1 MOL        -0.3404
     42 CBN         1.7970   -6.7560   26.8310 C.3       1 MOL        -0.0152
     43 CBO         4.2480   -5.9010   27.1210 C.2       1 MOL         0.2444
     44 NBP         2.7470   -6.7240   29.1320 N.am      1 MOL        -0.2737
     45 CBQ         4.1050   -9.7400   26.1140 C.3       1 MOL        -0.0651
     46 OBR         0.7400  -11.4340   33.5500 O.2       1 MOL        -0.3774
     47 OBT        -0.5890  -12.6520   32.2310 O.3       1 MOL        -0.2602
     48 CBX         3.5730   -6.5220   32.4150 C.3       1 MOL         0.0213
     49 CBY         2.9130   -7.3220   31.3040 C.3       1 MOL         0.1364
     50 NBZ         2.9360   -8.7200   31.7840 N.am      1 MOL        -0.2468
     51 CCA         3.6130   -8.7310   33.0750 C.3       1 MOL         0.0683
     52 CCB         3.4360   -7.4130   33.6420 C.3       1 MOL         0.1116
     53 CG1         5.1000  -10.8780   31.0950 C.3       1 MOL        -0.0558
     54 CG2         3.7310  -12.3340   29.7660 C.3       1 MOL        -0.0558
     55 H1          1.1873  -12.2013   30.6261 H         1 MOL         0.1899
     56 H2          2.7751  -10.8685   32.7469 H         1 MOL         0.0805
     57 H3         -0.6028   -3.1339   37.2803 H         1 MOL         0.0637
     58 H4          4.1686   -4.1467   36.8139 H         1 MOL         0.0508
     59 H5         -3.3367  -13.2726   32.0308 H         1 MOL         0.0297
     60 H6         -3.5543  -13.7232   33.7560 H         1 MOL         0.0297
     61 H7         -2.5064  -10.9273   32.7659 H         1 MOL         0.0330
     62 H8         -1.0133  -13.3988   34.1390 H         1 MOL         0.0650
     63 H9          8.5641   -1.5102   28.0575 H         1 MOL         0.0592
     64 H10         5.4453   -1.1332   29.1994 H         1 MOL         0.0592
     65 H11         5.0703  -13.4370   31.7984 H         1 MOL         0.0237
     66 H12         3.3162  -13.5565   32.1666 H         1 MOL         0.0237
     67 H13         4.3616  -12.4525   33.1232 H         1 MOL         0.0237
     68 H14         3.8042   -7.7633   25.4214 H         1 MOL         0.0265
     69 H15         2.4213   -8.8804   25.1634 H         1 MOL         0.0265
     70 H16        -1.7644  -11.6869   35.4735 H         1 MOL         0.0269
     71 H17        -3.5512  -11.6669   35.2897 H         1 MOL         0.0269
     72 H18         4.7469   -5.0912   28.9092 H         1 MOL         0.2148
     73 H19         2.0937   -8.7903   27.7146 H         1 MOL         0.0312
     74 H20        -0.9884   -9.1552   33.6351 H         1 MOL         0.0267
     75 H21        -0.4743   -9.9495   35.1620 H         1 MOL         0.0267
     76 H22         1.0413   -1.7507   38.4332 H         1 MOL         0.0606
     77 H23         5.4056   -1.4563   38.9489 H         1 MOL         0.0580
     78 H24         5.2715   -2.1429   37.2944 H         1 MOL         0.0580
     79 H25         5.1704   -3.2231   38.7260 H         1 MOL         0.0580
     80 H26        -2.9982   -9.4857   35.8306 H         1 MOL         0.0265
     81 H27        -3.2157   -9.4785   34.0476 H         1 MOL         0.0265
     82 H28        -0.3931   -8.0481   36.1890 H         1 MOL         0.0291
     83 H29        -2.0883   -7.6774   35.7246 H         1 MOL         0.0291
     84 H30        -1.4546   -6.2470   34.1598 H         1 MOL         0.0462
     85 H31        -0.1956   -7.3608   33.5266 H         1 MOL         0.0462
     86 H32         7.1305   -3.6972   29.7676 H         1 MOL         0.0647
     87 H33         1.8314   -6.2994   25.8309 H         1 MOL         0.0279
     88 H34         0.8009   -6.6007   27.2710 H         1 MOL         0.0279
     89 H35         1.9204   -6.2577   29.4471 H         1 MOL         0.1839
     90 H36         4.5456  -10.0651   25.1600 H         1 MOL         0.0230
     91 H37         3.5244  -10.5662   26.5501 H         1 MOL         0.0230
     92 H38         4.9072   -9.4492   26.8081 H         1 MOL         0.0230
     93 H39         3.0548   -5.5638   32.5678 H         1 MOL         0.0343
     94 H40         4.6320   -6.3335   32.1850 H         1 MOL         0.0343
     95 H41         1.8739   -6.9748   31.2053 H         1 MOL         0.0803
     96 H42         4.6833   -8.9465   32.9411 H         1 MOL         0.0554
     97 H43         3.1654   -9.4908   33.7325 H         1 MOL         0.0554
     98 H44         4.1988   -7.1681   34.3958 H         1 MOL         0.0683
     99 H45         4.9145  -10.0579   30.3858 H         1 MOL         0.0237
    100 H46         5.9734  -11.4589   30.7636 H         1 MOL         0.0237
    101 H47         5.2944  -10.4615   32.0944 H         1 MOL         0.0237
    102 H48         2.8573  -13.0020   29.7472 H         1 MOL         0.0237
    103 H49         4.6319  -12.9007   29.4880 H         1 MOL         0.0237
    104 H50         3.5796  -11.5122   29.0507 H         1 MOL         0.0237
@<TRIPOS>BOND
     1    1    3 2  
     2    4    1 1  
     3    1   50 am 
     4    2    4 1  
     5    6    2 am 
     6    4    5 1  
     7    5   20 1  
     8    5   53 1  
     9    5   54 1  
    10    6   46 2  
    11   47    6 1  
    12   33    7 2  
    13    7   35 1  
    14   22    8 2  
    15    8   27 1  
    16   35    9 2  
    17    9   38 1  
    18   11   10 1  
    19   12   10 1  
    20   11   12 1  
    21   23   11 1  
    22   12   47 1  
    23   14   13 2  
    24   40   13 1  
    25   40   14 1  
    26   16   15 1  
    27   24   16 1  
    28   16   39 1  
    29   16   40 1  
    30   17   25 1  
    31   17   42 1  
    32   17   43 1  
    33   44   17 1  
    34   19   18 2  
    35   19   44 am 
    36   49   19 1  
    37   25   21 1  
    38   21   45 1  
    39   35   22 1  
    40   36   22 1  
    41   31   23 1  
    42   43   24 am 
    43   42   25 1  
    44   26   31 1  
    45   32   26 1  
    46   38   27 2  
    47   28   33 1  
    48   52   28 1  
    49   30   29 1  
    50   38   30 1  
    51   37   32 1  
    52   33   34 1  
    53   34   36 2  
    54   34   37 1  
    55   43   41 2  
    56   48   49 1  
    57   48   52 1  
    58   49   50 1  
    59   50   51 1  
    60   51   52 1  
    61    2   55 1  
    62    4   56 1  
    63    8   57 1  
    64    9   58 1  
    65   10   59 1  
    66   10   60 1  
    67   11   61 1  
    68   12   62 1  
    69   13   63 1  
    70   14   64 1  
    71   20   65 1  
    72   20   66 1  
    73   20   67 1  
    74   21   68 1  
    75   21   69 1  
    76   23   70 1  
    77   23   71 1  
    78   24   72 1  
    79   25   73 1  
    80   26   74 1  
    81   26   75 1  
    82   27   76 1  
    83   29   77 1  
    84   29   78 1  
    85   29   79 1  
    86   31   80 1  
    87   31   81 1  
    88   32   82 1  
    89   32   83 1  
    90   37   84 1  
    91   37   85 1  
    92   40   86 1  
    93   42   87 1  
    94   42   88 1  
    95   44   89 1  
    96   45   90 1  
    97   45   91 1  
    98   45   92 1  
    99   48   93 1  
   100   48   94 1  
   101   49   95 1  
   102   51   96 1  
   103   51   97 1  
   104   52   98 1  
   105   53   99 1  
   106   53  100 1  
   107   53  101 1  
   108   54  102 1  
   109   54  103 1  
   110   54  104 1

**Comment by stefdoerr** [comment]
I think CGenFF is not really supported anymore. @raimis opinions?

**Comment by stefdoerr** [comment]
I gave it a few tries but `match` seems to either run out of memory or straight-up segfault. So I don't think I can be of much help on this. I would suggest using AMBER+GAFF2 or reporting the issue to the `match` team.

**Comment by stefdoerr** [comment]
The issue doesn't seem to be on our side at least. I fixed your mol2 file a bit anyway to fix it's parsing

```
@<TRIPOS>MOLECULE
3MOL_MOLand
104 110 0 0 0
SMALL
USER_CHARGES


@<TRIPOS>ATOM
1 C 2.4760 -9.7570 31.1330 C.2 1 MOL 0.2070
2 N 1.3770 -11.7780 31.5120 N.am 1 MOL -0.2407
3 O 1.9560 -9.6360 30.0650 O.2 1 MOL -0.3942
4 CA 2.6250 -11.0070 31.6660 C.3 1 MOL 0.1378
5 CB 3.9010 -11.7690 31.1510 C.3 1 MOL 0.0025
6 CAB 0.4870 -11.9400 32.4950 C.2 1 MOL 0.3221
7 NAC 2.5950 -5.6560 35.5540 N.ar 1 MOL -0.2649
8 CAD 0.4540 -3.3530 37.1790 C.ar 1 MOL -0.0425
9 CAE 3.1150 -3.9150 36.9200 C.ar 1 MOL -0.0161
10 CAF -2.9650 -13.1150 33.0540 C.3 1 MOL -0.0165
11 CAG -2.4620 -11.7730 33.4680 C.3 1 MOL -0.0077
12 CAH -1.5080 -12.8960 33.2950 C.3 1 MOL 0.0914
13 CAK 7.6460 -1.9430 28.4520 C.2 1 MOL -0.0560
14 CAL 6.2860 -1.7790 28.9500 C.2 1 MOL -0.0560
15 OAM 5.8900 -3.4560 26.3170 O.2 1 MOL -0.1497
16 SAN 6.2200 -4.2460 27.4200 S.O2 1 MOL 0.0716
17 CAO 3.0140 -6.7220 27.7090 C.3 1 MOL 0.1374
18 OAP 4.5290 -7.8200 29.7450 O.2 1 MOL -0.3947
19 CAQ 3.4920 -7.2800 30.0230 C.2 1 MOL 0.2013
20 CAR 4.1810 -12.8780 32.1250 C.3 1 MOL -0.0558
21 CAS 3.2000 -8.5640 25.8730 C.3 1 MOL -0.0516
22 CAT 0.8600 -4.3950 36.4100 C.ar 1 MOL 0.0479
23 CAU -2.6010 -11.3050 34.8700 C.3 1 MOL -0.0474
24 NAV 4.9830 -5.1230 27.9380 N.am 1 MOL -0.1546
25 CAW 2.5120 -7.9920 27.0840 C.3 1 MOL -0.0066
26 CAX -1.2050 -9.2640 34.7080 C.3 1 MOL -0.0510
27 CAY 1.3730 -2.5830 37.8230 C.ar 1 MOL -0.0236
28 OAZ 2.1540 -7.4020 34.2250 O.3 1 MOL -0.2852
29 CBA 4.9190 -2.2270 38.3330 C.3 1 MOL 0.0605
30 OBB 3.5620 -2.0510 38.3700 O.3 1 MOL -0.3183
31 CBC -2.5850 -9.8380 34.8740 C.3 1 MOL -0.0525
32 CBD -1.0960 -7.9650 35.3470 C.3 1 MOL -0.0406
33 CBE 1.7410 -6.3910 34.9400 C.ar 1 MOL 0.1985
34 CBF 0.3710 -6.1430 35.0590 C.ar 1 MOL 0.0906
35 CBG 2.1960 -4.6710 36.2800 C.ar 1 MOL 0.0423
36 NBH -0.0160 -5.1350 35.8010 N.ar 1 MOL -0.2829
37 CBI -0.6130 -6.9000 34.4340 C.3 1 MOL 0.0041
38 CBJ 2.7250 -2.8500 37.7080 C.ar 1 MOL 0.0960
39 OBK 7.2670 -5.0730 26.9790 O.2 1 MOL -0.1497
40 CBL 6.8750 -3.1150 28.8700 C.3 1 MOL 0.1367
41 OBM 4.4810 -5.9790 25.9480 O.2 1 MOL -0.3404
42 CBN 1.7970 -6.7560 26.8310 C.3 1 MOL -0.0152
43 CBO 4.2480 -5.9010 27.1210 C.2 1 MOL 0.2444
44 NBP 2.7470 -6.7240 29.1320 N.am 1 MOL -0.2737
45 CBQ 4.1050 -9.7400 26.1140 C.3 1 MOL -0.0651
46 OBR 0.7400 -11.4340 33.5500 O.2 1 MOL -0.3774
47 OBT -0.5890 -12.6520 32.2310 O.3 1 MOL -0.2602
48 CBX 3.5730 -6.5220 32.4150 C.3 1 MOL 0.0213
49 CBY 2.9130 -7.3220 31.3040 C.3 1 MOL 0.1364
50 NBZ 2.9360 -8.7200 31.7840 N.am 1 MOL -0.2468
51 CCA 3.6130 -8.7310 33.0750 C.3 1 MOL 0.0683
52 CCB 3.4360 -7.4130 33.6420 C.3 1 MOL 0.1116
53 CG1 5.1000 -10.8780 31.0950 C.3 1 MOL -0.0558
54 CG2 3.7310 -12.3340 29.7660 C.3 1 MOL -0.0558
55 H1 1.1873 -12.2013 30.6261 H 1 MOL 0.1899
56 H2 2.7751 -10.8685 32.7469 H 1 MOL 0.0805
57 H3 -0.6028 -3.1339 37.2803 H 1 MOL 0.0637
58 H4 4.1686 -4.1467 36.8139 H 1 MOL 0.0508
59 H5 -3.3367 -13.2726 32.0308 H 1 MOL 0.0297
60 H6 -3.5543 -13.7232 33.7560 H 1 MOL 0.0297
61 H7 -2.5064 -10.9273 32.7659 H 1 MOL 0.0330
62 H8 -1.0133 -13.3988 34.1390 H 1 MOL 0.0650
63 H9 8.5641 -1.5102 28.0575 H 1 MOL 0.0592
64 H10 5.4453 -1.1332 29.1994 H 1 MOL 0.0592
65 H11 5.0703 -13.4370 31.7984 H 1 MOL 0.0237
66 H12 3.3162 -13.5565 32.1666 H 1 MOL 0.0237
67 H13 4.3616 -12.4525 33.1232 H 1 MOL 0.0237
68 H14 3.8042 -7.7633 25.4214 H 1 MOL 0.0265
69 H15 2.4213 -8.8804 25.1634 H 1 MOL 0.0265
70 H16 -1.7644 -11.6869 35.4735 H 1 MOL 0.0269
71 H17 -3.5512 -11.6669 35.2897 H 1 MOL 0.0269
72 H18 4.7469 -5.0912 28.9092 H 1 MOL 0.2148
73 H19 2.0937 -8.7903 27.7146 H 1 MOL 0.0312
74 H20 -0.9884 -9.1552 33.6351 H 1 MOL 0.0267
75 H21 -0.4743 -9.9495 35.1620 H 1 MOL 0.0267
76 H22 1.0413 -1.7507 38.4332 H 1 MOL 0.0606
77 H23 5.4056 -1.4563 38.9489 H 1 MOL 0.0580
78 H24 5.2715 -2.1429 37.2944 H 1 MOL 0.0580
79 H25 5.1704 -3.2231 38.7260 H 1 MOL 0.0580
80 H26 -2.9982 -9.4857 35.8306 H 1 MOL 0.0265
81 H27 -3.2157 -9.4785 34.0476 H 1 MOL 0.0265
82 H28 -0.3931 -8.0481 36.1890 H 1 MOL 0.0291
83 H29 -2.0883 -7.6774 35.7246 H 1 MOL 0.0291
84 H30 -1.4546 -6.2470 34.1598 H 1 MOL 0.0462
85 H31 -0.1956 -7.3608 33.5266 H 1 MOL 0.0462
86 H32 7.1305 -3.6972 29.7676 H 1 MOL 0.0647
87 H33 1.8314 -6.2994 25.8309 H 1 MOL 0.0279
88 H34 0.8009 -6.6007 27.2710 H 1 MOL 0.0279
89 H35 1.9204 -6.2577 29.4471 H 1 MOL 0.1839
90 H36 4.5456 -10.0651 25.1600 H 1 MOL 0.0230
91 H37 3.5244 -10.5662 26.5501 H 1 MOL 0.0230
92 H38 4.9072 -9.4492 26.8081 H 1 MOL 0.0230
93 H39 3.0548 -5.5638 32.5678 H 1 MOL 0.0343
94 H40 4.6320 -6.3335 32.1850 H 1 MOL 0.0343
95 H41 1.8739 -6.9748 31.2053 H 1 MOL 0.0803
96 H42 4.6833 -8.9465 32.9411 H 1 MOL 0.0554
97 H43 3.1654 -9.4908 33.7325 H 1 MOL 0.0554
98 H44 4.1988 -7.1681 34.3958 H 1 MOL 0.0683
99 H45 4.9145 -10.0579 30.3858 H 1 MOL 0.0237
100 H46 5.9734 -11.4589 30.7636 H 1 MOL 0.0237
101 H47 5.2944 -10.4615 32.0944 H 1 MOL 0.0237
102 H48 2.8573 -13.0020 29.7472 H 1 MOL 0.0237
103 H49 4.6319 -12.9007 29.4880 H 1 MOL 0.0237
104 H50 3.5796 -11.5122 29.0507 H 1 MOL 0.0237
@<TRIPOS>BOND
1 1 3 2
2 4 1 1
3 1 50 am
4 2 4 1
5 6 2 am
6 4 5 1
7 5 20 1
8 5 53 1
9 5 54 1
10 6 46 2
11 47 6 1
12 33 7 2
13 7 35 1
14 22 8 2
15 8 27 1
16 35 9 2
17 9 38 1
18 11 10 1
19 12 10 1
20 11 12 1
21 23 11 1
22 12 47 1
23 14 13 2
24 40 13 1
25 40 14 1
26 16 15 1
27 24 16 1
28 16 39 1
29 16 40 1
30 17 25 1
31 17 42 1
32 17 43 1
33 44 17 1
34 19 18 2
35 19 44 am
36 49 19 1
37 25 21 1
38 21 45 1
39 35 22 1
40 36 22 1
41 31 23 1
42 43 24 am
43 42 25 1
44 26 31 1
45 32 26 1
46 38 27 2
47 28 33 1
48 52 28 1
49 30 29 1
50 38 30 1
51 37 32 1
52 33 34 1
53 34 36 2
54 34 37 1
55 43 41 2
56 48 49 1
57 48 52 1
58 49 50 1
59 50 51 1
60 51 52 1
61 2 55 1
62 4 56 1
63 8 57 1
64 9 58 1
65 10 59 1
66 10 60 1
67 11 61 1
68 12 62 1
69 13 63 1
70 14 64 1
71 20 65 1
72 20 66 1
73 20 67 1
74 21 68 1
75 21 69 1
76 23 70 1
77 23 71 1
78 24 72 1
79 25 73 1
80 26 74 1
81 26 75 1
82 27 76 1
83 29 77 1
84 29 78 1
85 29 79 1
86 31 80 1
87 31 81 1
88 32 82 1
89 32 83 1
90 37 84 1
91 37 85 1
92 40 86 1
93 42 87 1
94 42 88 1
95 44 89 1
96 45 90 1
97 45 91 1
98 45 92 1
99 48 93 1
100 48 94 1
101 49 95 1
102 51 96 1
103 51 97 1
104 52 98 1
105 53 99 1
106 53 100 1
107 53 101 1
108 54 102 1
109 54 103 1
110 54 104 1
```

**Comment by jnoske** [comment]
Thank you very much, I reported the issue to the MATCH team.
